
select name from sys.tables

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'Patients'

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'Medicalstaff'

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'VitalSigns'

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'Admissions'

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'BILLING'

select COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'INSURANCE'


-- Creating Primary keys
exec sp_help 'patients'
ALTER TABLE PATIENTS
--ALTER COLUMN PATIENT_ID NVARCHAR(100) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL
ADD CONSTRAINT PK_PATIENTS PRIMARY KEY(PATIENT_ID)

ALTER TABLE PATIENTS DROP CONSTRAINT PK_PATIENTS;

exec sp_help 'doctors'
ALTER TABLE DOCTORS
--ALTER COLUMN DOCTOR_ID smallint NOT NULL
ADD CONSTRAINT PK_DOCTORS PRIMARY KEY(DOCTOR_ID)

ALTER TABLE DOCTORS
DROP CONSTRAINT PK_DOCTORS

exec sp_help 'nurses'
ALTER TABLE NURSES
--ALTER COLUMN NURSE_ID SMALLINT NOT NULL
ADD CONSTRAINT PK_NURSES PRIMARY KEY(NURSE_ID)

ALTER TABLE NURSES
DROP CONSTRAINT PK_NURSES

exec sp_help 'billing'
ALTER TABLE BILLING
--ALTER COLUMN BILLING_ID INT NOT NULL
ADD CONSTRAINT PK_BILLING PRIMARY KEY(BILLING_ID)

exec sp_help 'insurance'
ALTER TABLE INSURANCE
--ALTER COLUMN INSURANCE_ID SMALLINT NOT NULL
ADD CONSTRAINT PK_INSURANCE PRIMARY KEY(INSURANCE_ID)

exec sp_help 'rooms'
ALTER TABLE ROOMS
--ALTER COLUMN ROOM_NUMBER INT NOT NULL
ADD CONSTRAINT PK_ROOMS PRIMARY KEY(ROOM_NUMBER)

exec sp_help 'medicalstaff'
ALTER TABLE MEDICALSTAFF
--ALTER COLUMN STAFF_ID INT NOT NULL
ADD CONSTRAINT PK_MEDICALSTAFF PRIMARY KEY(STAFF_ID)



exec sp_help 'admissions'
ALTER TABLE ADMISSIONS
--ALTER COLUMN ADMISSION_ID INT NOT NULL
ADD CONSTRAINT PK_ADMISSIONS PRIMARY KEY(ADMISSION_ID)

--**********************************************************
--**********************************************************

--Creating Foreign keys

--DOCTORS
ALTER TABLE DOCTORS
ADD CONSTRAINT FK_DOCTORS_MEDICALSTAFF FOREIGN KEY(DOCTOR_ID)
REFERENCES MEDICALSTAFF(STAFF_ID)
ON DELETE CASCADE
ON UPDATE CASCADE


--NURSES
ALTER TABLE NURSES
ADD CONSTRAINT FK_NURSES_MEDICALSTAFF FOREIGN KEY(NURSE_ID)
REFERENCES MEDICALSTAFF(STAFF_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE NURSES
ALTER COLUMN NURSE_ID INT 

--BILLING
ALTER TABLE BILLING 
ADD CONSTRAINT FK_BILLING_PATIENTS FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID)
ON DELETE CASCADE
ON UPDATE CASCADE


ALTER TABLE BILLING 
ADD CONSTRAINT FK_BILLING_INSURANCE FOREIGN KEY(INSURANCE_ID)
REFERENCES INSURANCE(INSURANCE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE


-- Insurance

ALTER TABLE INSURANCE
ADD CONSTRAINT FK_INSURANCE_PATIENTS FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID)


-- VitalSigns

ALTER TABLE VITALSIGNS
ADD CONSTRAINT FK_VITALSIGNS_PATIENTS FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID)
ON DELETE CASCADE
ON UPDATE CASCADE



ALTER TABLE VITALSIGNS
ADD CONSTRAINT FK_VITALSIGNS_MEDICALSTAFF FOREIGN KEY(RECORDED_BY)
REFERENCES MEDICALSTAFF(STAFF_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE


-- ADMISSIONS

ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_PATIENTS FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID)
ON UPDATE CASCADE
ON DELETE CASCADE


ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_MS_DCTR FOREIGN KEY(DOCTOR_ID)
REFERENCES MEDICALSTAFF(STAFF_ID)
ON UPDATE CASCADE
ON DELETE CASCADE


ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_MS_NRS FOREIGN KEY(NURSE_ID)
REFERENCES MEDICALSTAFF(STAFF_ID)


ALTER TABLE ADMISSIONS 
ADD CONSTRAINT FK_ADMISSIONS_ROOMS FOREIGN KEY(ROOM_NUMBER)
REFERENCES ROOMS(ROOM_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE


-- Indexes for Performance

CREATE INDEX idx_patient_name ON Patients(last_name, first_name);
CREATE INDEX idx_admission_dates ON Admissions(admission_date, discharge_date);
CREATE INDEX idx_patient_admission ON Admissions(patient_id);
CREATE INDEX idx_doctor_admissions ON Admissions(doctor_id);
CREATE INDEX idx_vital_signs_date ON VitalSigns(patient_id, recorded_at);